# This is a basic workflow to help you get started with Actions

name: DEploy IaC Demo

# Controls when the workflow will run
on:   workflow_dispatch
  # Triggers the workflow on push or pull request events but only for the "main" branc
env:
  AZURE_RG: Bicep_Zone
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-bicep-template:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: Deploy Bicep Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.AZURE_RG }}
        template: ./lab0/main.bicep
        parameters: ./lab0/parameters.json
        failOnStdErr: false